
process.on('unhandledRejection', (err, promise) => {
  console.error(err);
});
